#ifndef PRIORITY_H
#define PRIORITY_H
namespace Priority
{
	const VMUINT8 WAKEUP=129;

	const VMUINT8 FALL_ALARM=136;

	const VMUINT8 COMMAND_RX=184;
	const VMUINT8 COMMAND_TX=192;

	const VMUINT8 DATA_FETCHER=225;

	const VMUINT8 DATA_COLLECTOR=233;

	const VMUINT8 MAIN_LOOP=245;

	const VMUINT8 BLUETOOTH_CONNECTOR=247;
}
#endif // PRIORITY_H

